image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0

  - command: git config --global user.email $GIT_COMMITTER_EMAIL

ports:
  - port: 1313
    onOpen: open-preview

vscode:
  extensions:
    - denoland.vscode-deno
