image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      deno bundle assets/ts/main.ts assets/js/script.js --config deno.json &&
      deno bundle assets/ts/search.ts assets/js/search.js --config deno.json
    command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0

  - command: deno bundle --watch assets/ts/main.ts assets/js/script.js --config deno.json
  - command: deno bundle --watch assets/ts/search.ts assets/js/search.js --config deno.json

  - command: git config --global user.email $GIT_COMMITTER_EMAIL

ports:
  - port: 1313
    onOpen: open-preview

vscode:
  extensions:
    - denoland.vscode-deno
