baseURL: "https://akimon658.github.io/"
defaultContentLanguage: "ja"
googleAnalytics: "UA-174918347-7"
languageCode: "ja"
publishDir: "docs"
theme: "fuji"
title: "Boring Time"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  link:
    - Name: "Email"
      URl: "mailto:akimo_greninja@yahoo.co.jp"

    - Name: "GitHub"
      URL: "https://github.com/Akimon658"

    - Name: "Twitter (about Pokémon)"
      URL: "https://twitter.com/Akimon658"

    - Name: "Twitter (other)"
      URL: "https://twitter.com/kimo_pk"

  nav:
    - Name: "About"
      URL: "about/"

Params:
  author: "Akimo"
