baseURL: "https://akimon658.github.io/"
defaultContentLanguage: "ja"
enableGitInfo: true
googleAnalytics: "UA-174918347-7"
hasCJKLanguage: true
languageCode: "ja"
publishDir: "docs"
theme: "fuji"
title: "Boring Time"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  link:
    - Name: "Email"
      URl: "mailto:akimo_greninja@yahoo.co.jp"

    - Name: "GitHub"
      URL: "https://github.com/Akimon658"

    - Name: "Twitter (Pokémon)"
      URL: "https://twitter.com/Akimon658"

    - Name: "Twitter (other)"
      URL: "https://twitter.com/kimo_pk"

  nav:
    - Name: "About"
      URL: "/about/"

    - Name: "Home"
      URL: "/"

    - Name: "Privacy Policy"
      URL: "/privacy-policy/"

Params:
  author: "Akimo"
  sourceURL: "https://github.com/Akimon658/akimon658.github.io"
