baseURL: "https://akimon658.github.io/"
defaultContentLanguage: "ja"
googleAnalytics: "UA-174918347-7"
languageCode: "ja"
publishDir: "docs"
theme: "fuji"
title: "Boring Time"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  link:
    - Name: "Twitter (@akimon658)"
      URL: "https://twitter.com/Akimon658"

    - Name: "Twitter (@kimo_pk)"
      URL: "https://twitter.com/kimo_pk"

  nav:
    - Name: "About"
      URL: "about/"

Params:
  author: "Akimo"
