Author = "Akimo"
baseURL = "https://akimon658.github.io/"
copyright = "© 2021 Akimo"
defaultContentLanguage = "ja"
googleAnalytics = "UA-174918347-7"
languageCode = "ja"
publishDir = "docs"
theme = "fuji"
title = "Boring Time"

[markup.goldmark.renderer]
unsafe = true
