baseURL: "https://akimon658.github.io/"
defaultContentLanguage: "ja"
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: "G-KWKSTPH28H"
hasCJKLanguage: true
languageCode: "ja"
publishDir: "docs"
summaryLength: 50
theme: "fuji"
title: "Boring Time"

build:
  noJSConfigInAssets: true

languages:
  ja:
    languageName: "日本語"
    dateFormat: 2006年1月2日
    weight: 1

  en:
    languageName: "English"
    weight: 2

    Menus:
      link:
        - Name: "Email"
          URl: "mailto:akimo_greninja@yahoo.co.jp"
          weight: 1

        - Name: "GitHub"
          URL: "https://github.com/Akimon658"
          weight: 2

        - Name: "Twitter (Pokémon)"
          URL: "https://twitter.com/Akimon658"
          weight: 3

        - Name: "Twitter (other)"
          URL: "https://twitter.com/kimo_pk"

      nav:
        - Name: "Home"
          URL: "/en/"
          weight: 1

        - Name: "Search"
          URL: "/en/search/"
          weight: 2

        - Name: "About"
          URL: "/en/about/"

        - Name: "Privacy Policy"
          URL: "/en/privacy-policy/"

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    noClasses: false

Menus:
  link:
    - Name: "Email"
      URl: "mailto:akimo_greninja@yahoo.co.jp"
      weight: 1

    - Name: "GitHub"
      URL: "https://github.com/Akimon658"
      weight: 2

    - Name: "Twitter (Pokémon)"
      URL: "https://twitter.com/Akimon658"
      weight: 3

    - Name: "Twitter (other)"
      URL: "https://twitter.com/kimo_pk"

  nav:
    - Name: "Home"
      URL: "/"
      weight: 1

    - Name: "Search"
      URL: "/search/"
      weight: 2

    - Name: "About"
      URL: "/about/"

    - Name: "Privacy Policy"
      URL: "/privacy-policy/"

outputFormats:
  SearchIndex:
    isPlaintext: true
    notAlternative: true
    mediaType: "application/json"
    path: "/search/"

outputs:
  home: ["HTML", "RSS", "SearchIndex"]

Params:
  author: "Akimo"
  copyrightStartYear: "2021"
  disqusShortname: "akimon658-github-io"
  microsoftClarity: "95k7fmhfca"
  sourceURL: "https://github.com/Akimon658/akimon658.github.io"

privacy:
  googleanalytics:
    respectDoNotTrack: true
