baseURL = "https://akimon658.github.io/"
defaultContentLanguage = "ja"
languageCode = "ja"
publishDir = "docs"
theme = "hugo-coder"
title = "飽きたら終わり"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true