baseURL: "https://akimon658.github.io/"
defaultContentLanguage: "ja"
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: "UA-174918347-7"
hasCJKLanguage: true
languageCode: "ja"
publishDir: "docs"
theme: "fuji"
title: "Boring Time"

languages:
  ja:
    weight: 1

  en:
    weight: 2

    Menus:
      link:
        - Name: "Email"
          URl: "mailto:akimo_greninja@yahoo.co.jp"
          weight: 1

        - Name: "GitHub"
          URL: "https://github.com/Akimon658"
          weight: 2

        - Name: "Twitter (Pokémon)"
          URL: "https://twitter.com/Akimon658"
          weight: 3

        - Name: "Twitter (other)"
          URL: "https://twitter.com/kimo_pk"

      nav:
        - Name: "About"
          URL: "/en/about/"

        - Name: "Home"
          URL: "/en/"

        - Name: "Privacy Policy"
          URL: "/en/privacy-policy/"

        - Name: "Search"
          URL: "/en/search/"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  link:
    - Name: "Email"
      URl: "mailto:akimo_greninja@yahoo.co.jp"
      weight: 1

    - Name: "GitHub"
      URL: "https://github.com/Akimon658"
      weight: 2

    - Name: "Twitter (Pokémon)"
      URL: "https://twitter.com/Akimon658"
      weight: 3

    - Name: "Twitter (other)"
      URL: "https://twitter.com/kimo_pk"

  nav:
    - Name: "About"
      URL: "/about/"

    - Name: "Home"
      URL: "/"

    - Name: "Privacy Policy"
      URL: "/privacy-policy/"

    - Name: "Search"
      URL: "/search/"

outputs:
  home: ["HTML", "RSS", "JSON"]

Params:
  author: "Akimo"
  disqusShortname: "akimon658-github-io"
  sourceURL: "https://github.com/Akimon658/akimon658.github.io"
