version: '3'

services:
  hugo:
    build: .
    volumes:
      - ../:/workspace
    ports:
      - '1313:1313'
    environment:
      TZ: Asia/Tokyo
    command: sleep infinity

  ogjson:
    image: akimon658/ogjson:1.1.0
    command: /ogjson -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
