name: Deploy

on:
  push:
    branches: [ main ]

    paths:
      - 'src/**'
      - '_config.ts'
      - 'deno.jsonc'
      - 'deno.lock'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DENO_DIR: ~/.deno

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('**/deno.lock') }}

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: |
          deno task lume
          touch public/.nojekyll

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
