name: Deploy

on:
  push:
    paths:
      - 'src/**'
      - '_config.ts'
      - 'deno.jsonc'
      - 'deno.lock'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Restore Deno cache
        uses: actions/cache/restore@v4
        id: deno-cache
        with:
          path: ~/.cache/deno
          key: deno-${{ hashFiles('deno.lock') }}
          restore-keys: deno-

      - name: Restore build cache
        uses: actions/cache/restore@v4
        id: build-cache
        with:
          path: _cache
          key: lume-${{ hashFiles('src/**', '_config.ts') }}
          restore-keys: lume-

      - name: Build
        run: |
          deno task lume
          touch public/.nojekyll

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public/ --project-name=akimon658
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Deno cache
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/deno
          key: deno-${{ hashFiles('deno.lock') }}

      - name: Save build cache
        uses: actions/cache/save@v4
        with:
          path: _cache
          key: lume-${{ hashFiles('src/**', '_config.ts') }}
