name: Deploy

on:
  push:
    branches: [ main ]

    paths:
      - 'archtypes/**'
      - 'assets/**'
      - 'content/**'
      - 'layouts/**'
      - 'static/**'
      - 'themes/**'
      - 'config.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Start containers
        run: |
          docker-compose up -d

      - name: Build
        run: |
          docker-compose exec -T --workdir /akimon658.github.io hugo \
          sh -c 'pnpm install && \
          hugo --minify && \
          touch public/.nojekyll'

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
