name: Update deno.lock

on:
  push:
    branches:
      - "renovate/**"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x


      - name: Restore Deno cache
        uses: actions/cache/restore@v4
        id: deno-cache
        with:
          path: ~/.cache/deno
          key: deno-${{ hashFiles('deno.lock') }}
          restore-keys: deno-

      - name: Restore build cache
        uses: actions/cache/restore@v4
        id: build-cache
        with:
          path: _cache
          key: lume-${{ hashFiles('src/**', '_config.ts') }}
          restore-keys: lume-

      - name: Update lockfile
        run: |
          rm deno.lock
          deno task serve &
          timeout=60
          until curl -s http://localhost:4000/ > /dev/null; do
            sleep 1;
            ((timeout--))

            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for server to start"
              exit 1
            fi
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update deno.lock"
          git push

      - name: Save Deno cache
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/deno
          key: deno-${{ hashFiles('deno.lock') }}

      - name: Save build cache
        uses: actions/cache/save@v4
        with:
          path: _cache
          key: lume-${{ hashFiles('src/**', '_config.ts') }}
