name: Update deno.lock

on:
  push:
    branches:
      - "renovate/**"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/deno
            _cache
          key: Default Cache

      - name: Update lockfile
        run: |
          rm deno.lock
          deno task lume &
          until (curl -s http://localhost:3000 > /dev/null); do
            sleep 1
          done

      - uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/deno
            _cache
          key: Default Cache

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update deno.lock"
          git push
