name: Update deno.lock

on:
  push:
    branches:
      - "renovate/**"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            ~/.cache/deno
            _cache
          key: Default Cache

      - name: Update lockfile
        run: |
          rm deno.lock
          deno task serve &
          timeout=60
          until curl -s http://localhost:4000/ > /dev/null; do
            sleep 1;
            ((timeout--))

            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for server to start"
              exit 1
            fi
          done

      - name: Delete previous cache
        if: ${{ steps.cache.outputs.cache-hit }}
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "Default Cache" --confirm

      - uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/deno
            _cache
          key: Default Cache

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update deno.lock"
          git push
